spring:
  profiles:
    active: 
      -dev

---    
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud1?characterEncoding=utf8&useSSL=false
    username: cboy
    password: Hellocboy12345_
    hikari:
      maximum-pool-size: 15
  http:
    encoding.charset: UTF-8
    encoding.force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  application:
    name: microservicecloud-dept

#mybatis
mybatis-plus:
  mapper-locations: classpath:/com/tianxin/springcloud/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tianxin.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新热加载mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #表前缀
    table-prefix: tx_

  configuration:
    map-underscore-to-camel-case: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-hystrix-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: tianxinweb-microservicecloud
  company.name: www.tianxinweb.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
spring:
  profiles:prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud2?characterEncoding=utf8&useSSL=false
    username: cboy
    password: Hellocboy12345_
    hikari:
      maximum-pool-size: 15
  http:
    encoding.charset: UTF-8
    encoding.force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  application:
    name: microservicecloud-dept

#mybatis
mybatis-plus:
  mapper-locations: classpath:/com/tianxin/springcloud/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.tianxin.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新热加载mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #表前缀
    table-prefix: tx_

  configuration:
    map-underscore-to-camel-case: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept-hystrix-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: tianxinweb-microservicecloud
  company.name: www.tianxinweb.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

